config/routes.rb
Rails.application.routes.draw do
  root "festivals#index"
  devise_for :users

  get 'my_bookings', to: 'user_bookings#index', as: 'user_bookings'

  resources :festivals do
    get 'check_availability', on: :member do
    end
    resources :bookings, only: [:new, :create]
    resources :love_pods, only: [:show]
  end

  resources :love_pods do
    get 'show_from_index', on: :member do
    end
  end
  resources :bookings, only: [:destroy, :index]

  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/models/love_pod.rb
class LovePod < ApplicationRecord
  has_many :available_slots, dependent: :destroy
  has_many :festival_love_pods, dependent: :destroy
  has_many :festivals, through: :festival_love_pods
  has_many :bookings, through: :available_slots
  has_one_attached :photo

  validates :name, :description, presence: true
  validates :capacity, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/love_pods_controller.rb
class LovePodsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  before_action :set_love_pod, only: [:show, :edit, :update, :destroy, :show_from_index]

  def index
    @love_pods = LovePod.all
  end

  def new
    @love_pod = LovePod.new
  end

  def create
    @love_pod = LovePod.new(love_pod_params)
    if @love_pod.save
      redirect_to @love_pod, notice: 'Love pod was successfully created.'
    else
      render :new
    end
  end

  def show
    @festival = Festival.find(params[:festival_id])
  end

  def show_from_index
  end

  def edit
  end

  def update
    if @love_pod.update(love_pod_params)
      redirect_to @love_pod, notice: 'Love pod was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @love_pod.destroy
    redirect_to love_pods_path, notice: 'Love pod was successfully destroyed.'
  end

  private

    def set_love_pod
      @love_pod = LovePod.find(params[:id])
    end

    def love_pod_params
      params.require(:love_pod).permit(:name, :description, :capacity,
                                      :availabilty_start_time, :availabilty_end_time,
                                      :photo)
    end
end

app/helpers/love_pods_helper.rb
module LovePodsHelper
end

app/views/love_pods/edit.html.erb
<% if user_signed_in? && current_user.admin? %>

  <h1>New Love Pod</h1>

  <%= form_with(model: @love_pod, local: true) do |form| %>
    <% if @love_pod.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@love_pod.errors.count, "error") %> prohibited this love pod from being saved:</h2>
        <ul>
          <% @love_pod.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name, 'Name' %>
      <%= form.text_field :name, id: :love_pod_name, class: 'form-control' %>
    </div>

    <div class="field">
      <%= form.label :description, 'Description' %>
      <%= form.text_area :description, id: :love_pod_description, class: 'form-control' %>
    </div>

    <div class="field">
      <%= form.label :capacity, 'Capacity' %>
      <%= form.number_field :capacity, id: :love_pod_capacity, class: 'form-control' %>
    </div>

    <div class="field">
      <%= form.label :availabilty_start_time, 'Available from ' %>
      <%= form.time_field :availabilty_start_time, id: :love_pod_availabilty_start_time, class: 'form-control', value: form.object.availabilty_start_time.strftime('%H:%M'),
        min: 'hh:mm:ss',
        max: 'hh:mm:ss'%>
    </div>

    <div class="field">
      <%= form.label :availabilty_end_time, 'until' %>
      <%= form.time_field :availabilty_end_time, id: :love_pod_availabilty_end_time, class: 'form-control', value: form.object.availabilty_end_time.strftime('%H:%M'),
        min: 'hh:mm:ss',
        max: 'hh:mm:ss' %>
    </div>

    <div class="actions">
      <%= form.submit 'Create Love Pod', class: 'btn btn-primary' %>
    </div>
  <% end %>

  <%= link_to 'Back to Love Pods', love_pods_path, class: 'btn btn-link' %>

<% else %>
  <p>You are not authorized to see this page.</p>
<% end %>

app/views/love_pods/index.html.erb
<% if user_signed_in? && current_user.admin? %>

  <div class="button-top">
    <%= link_to 'New love pod', new_love_pod_path, class: 'butt button-pink' %>
  </div>

  <div class="cards-list">
    <% @love_pods.each do |love_pod| %>
      <div class="card card-spacing">
        <% if love_pod.photo.attached? %>
          <%= link_to cl_image_tag(love_pod.photo.key), show_from_index_love_pod_path(love_pod) %>
        <% else %>
          <%= link_to cl_image_tag(love_pod.image_url), show_from_index_love_pod_path(love_pod) %>
        <% end %>
        <h3><%= link_to love_pod.name, show_from_index_love_pod_path(love_pod) %></h3>
        <p><%= love_pod.description %></p>

        <div class="butt-list">
          <%= link_to 'Edit', edit_love_pod_path(love_pod), class: 'butt button-white' %>
          <%= link_to 'Delete', love_pod_path(love_pod), method: :delete, data: { confirm: 'Are you sure?' }, class: 'butt button-white' %>
        </div>
      </div>
    <% end %>
  </div>

<% else %>
  <p>You are not authorized to see this page.</p>
<% end %>

app/views/love_pods/new.html.erb
<!-- app/views/love_pods/new.html.erb -->
<% if user_signed_in? && current_user.admin? %>

  <h1 class="page-title">Create a new Love Pod</h1>

  <%= form_with(model: @love_pod, local: true) do |form| %>
    <% if @love_pod.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@love_pod.errors.count, "error") %> prohibited this love pod from being saved:</h2>
        <ul>
          <% @love_pod.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, id: :love_pod_name, class: 'form-input' %>
    </div>

    <div class="field">
      <%= form.label :description, class: 'form-label' %>
      <%= form.text_area :description, id: :love_pod_description, class: 'form-input' %>
    </div>

    <div class="field">
      <%= form.label :capacity, class: 'form-label' %>
      <%= form.number_field :capacity, id: :love_pod_capacity, class: 'form-input' %>
    </div>

      <div class="field">
      <%= form.label :availabilty_start_time, 'Available from ' %>
      <%= form.time_field :availabilty_start_time, id: :love_pod_availabilty_start_time, class: 'form-control', value: form.object.availabilty_start_time.strftime('%H:%M'),
        min: 'hh:mm:ss',
        max: 'hh:mm:ss'%>
    </div>

    <div class="field">
      <%= form.label :availabilty_end_time, 'until' %>
      <%= form.time_field :availabilty_end_time, id: :love_pod_availabilty_end_time, class: 'form-control', value: form.object.availabilty_end_time.strftime('%H:%M'),
        min: 'hh:mm:ss',
        max: 'hh:mm:ss' %>
    </div>

      <div class="field">
      <%= form.label :photo %>
      <%= form.file_field :photo, id: :love_pod_photo %>
    </div>

    <div class="butt-list">
      <%= form.submit 'Create Love Pod', class: 'butt button-pink' %>

  <% end %>
  <%= link_to 'Back to Love Pods', love_pods_path, class: 'butt button-white' %>
    </div>

<% else %>
  <p>You are not authorized to see this page.</p>
<% end %>

app/views/love_pods/show.html.erb
<div class="card">
  <% if @love_pod.photo.attached? %>
    <%= cl_image_tag(@love_pod.photo.key) %>
  <% else %>
    <%= cl_image_tag(@love_pod.image_url) %>
  <% end %>
  <h2><%= @love_pod.name %></h1>

  <p>
    <strong>Description:</strong>
    <%= @love_pod.description %>
  </p>

  <p>
    <strong>Capacity:</strong>
    <%= @love_pod.capacity %>
  </p>

  <p>
    <strong>Availability time frame:</strong>
    <%= @love_pod.availabilty_start_time.strftime("%H:%M") %> - <%= @love_pod.availabilty_end_time.strftime("%H:%M")  %>
  </p>

  <div class="butt-list">
    <%= link_to 'Back to festival', festival_path(@festival), class: 'butt button-white' %>
    <%= link_to 'Back to my bookings', user_bookings_path, class: 'butt button-white' %>
  </div>
</div>

app/views/love_pods/show_from_index.html.erb
<% if user_signed_in? && current_user.admin? %>

  <div class="card">
    <% if @love_pod.photo.attached? %>
      <%= cl_image_tag(@love_pod.photo.key) %>
    <% else %>
      <%= cl_image_tag(@love_pod.image_url) %>
    <% end %>
    <h2><%= @love_pod.name %></h1>

    <p>
      <strong>Description:</strong>
      <%= @love_pod.description %>
    </p>

    <p>
      <strong>Capacity:</strong>
      <%= @love_pod.capacity %>
    </p>

    <p>
      <strong>Availability time frame:</strong>
      <%= @love_pod.availabilty_start_time.strftime("%H:%M") %> - <%= @love_pod.availabilty_end_time.strftime("%H:%M")  %>
    </p>

    <div class="butt-list">
      <%= link_to 'Edit', edit_love_pod_path(@love_pod), class: 'butt button-blue' %>
      <%= link_to 'Delete', love_pod_path(@love_pod),
                  method: :delete,
                  data: { confirm: 'Are you sure?' },
                  class: 'butt button-blue' %>
      <%= link_to 'Back to Love Pods', love_pods_path, class: 'butt button-white' %>
    </div>
  </div>

<% else %>
  <p>You are not authorized to see this page.</p>
<% end %>