config/routes.rb
Rails.application.routes.draw do
  root "festivals#index"
  devise_for :users

  get 'my_bookings', to: 'user_bookings#index', as: 'user_bookings'

  resources :festivals do
    get 'check_availability', on: :member do
    end
    resources :bookings, only: [:new, :create]
    resources :love_pods, only: [:show]
  end

  resources :love_pods do
    get 'show_from_index', on: :member do
    end
  end
  resources :bookings, only: [:destroy, :index]

  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <%= link_to root_path, class: 'navbar-brand' do %>
    <%= cl_image_tag('logo_keco3w', alt: 'LOV+R Booking App', style: 'height: 40px;') %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item"><%= link_to 'Festivals', root_path, class: 'nav-link' %></li>
      <% if user_signed_in? %>
        <% if current_user.admin? %>
          <li class="nav-item"><%= link_to 'Love Pods', love_pods_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'See all bookings', bookings_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Add a new festival',  new_festival_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Add a new Love Pod',  new_love_pod_path, class: 'nav-link'%></li>
          <% else %>
          <li class="nav-item"><%= link_to 'My bookings', user_bookings_path, class: 'nav-link' %></li>
        <% end %>
          <li class="nav-item"><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
      <% else %>
        <li class="nav-item"><%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %></li>
        <% end %>
    </ul>
  </div>
</nav>