config/routes.rb
Rails.application.routes.draw do
  root "festivals#index"
  devise_for :users

  get 'my_bookings', to: 'user_bookings#index', as: 'user_bookings'

  resources :festivals do
    get 'check_availability', on: :member do
    end
    resources :bookings, only: [:new, :create]
    resources :love_pods, only: [:show]
  end

  resources :love_pods do
    get 'show_from_index', on: :member do
    end
  end
  resources :bookings, only: [:destroy, :index]

  mount StripeEvent::Engine, at: '/stripe-webhooks'
end

app/models/festival.rb
class Festival < ApplicationRecord
  has_many :festival_love_pods, dependent: :destroy
  has_many :love_pods, through: :festival_love_pods
  has_many :available_slots, dependent: :destroy
  has_many :bookings, through: :available_slots, dependent: :destroy
  has_one_attached :photo
  
  validates :name ,:location, :start_date, :end_date, presence: true
end

app/controllers/festivals_controller.rb
class FestivalsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show, :check_availability]
  before_action :set_festival, only: [:edit, :update, :destroy, :show, :check_availability]
  before_action :set_available_slots, only: [:check_availability, :update]

  def index
    @festivals = Festival.all
  end

  def show
  end

  def new
    @festival = Festival.new
  end

  def edit
  end

  def create
    @festival = Festival.new(festival_params)
    if @festival.save
      slots = create_available_slot_instances(@festival)
      slots.each { |slot| slot.save }
      redirect_to @festival, notice: 'Festival was successfully created.'
    else
      render :new
    end
  end

  def update
    if @festival.update(festival_params)
      update_available_slots(@festival)
      redirect_to @festival, notice: 'Festival was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @festival.destroy
    redirect_to festivals_path, notice: 'Festival was successfully deleted.'
  end

  def check_availability
    @date = params[:booking_date]
    @duration = params[:duration].to_i

    @start_date = @festival.start_date
    @end_date = @festival.end_date
    @date_options = []
    (@start_date..@end_date).each_with_index do |date, index|
      @date_options << ["Day #{index + 1} (#{date.strftime('%a %d %b %Y')})", date.to_s]
    end

    if @date.present? && @duration.present?
      @festival_slots
    else
      @festival_slots = []
    end
    render :check_availability
  end

  private

  def set_festival
    @festival = Festival.find(params[:id])
  end

  def set_available_slots
    @festival_slots = AvailableSlot.where(festival: @festival)
  end

  def update_available_slots(festival)
    old_slots = AvailableSlot.all.select do |slot|
      slot.festival = festival
    end
    updated_slots = create_available_slot_instances(festival)

    updated_slots.each do |new_slot|
      matching_old_slot = old_slots.find do |old_slot|
        old_slot.date == new_slot.date &&
          old_slot.time_frame == new_slot.time_frame &&
          old_slot.start_time == new_slot.start_time &&
          old_slot.duration == new_slot.duration &&
          old_slot.love_pod_id == new_slot.love_pod_id
      end

      if matching_old_slot
        matching_old_slot.attributes = new_slot.attributes
      else
        new_slot.save
      end
    end

    old_slots.each do |old_slot|
      unless updated_slots.any? { |new_slot| new_slot.attributes == old_slot.attributes }
        old_slot.destroy
      end
    end
  end


  def create_available_slot_instances(festival)
    start_date = festival.start_date
    end_date = festival.end_date
    durations = [25, 55]
    slots = []

    durations.each do |duration|
      (start_date..end_date).each do |date|
        festival.love_pods.each do |pod|

        start_time = pod.availabilty_start_time
        end_time = pod.availabilty_end_time

          while start_time + duration.minutes <= end_time
            time_frame = "#{start_time.strftime('%H:%M')} - #{(start_time + duration.minutes).strftime('%H:%M')}"

            slots << AvailableSlot.new(date: date,
            time_frame: time_frame,
            start_time: start_time,
            duration: duration, festival: festival,
            love_pod: pod,
            price: 10)

            start_time += (duration + 5).minutes
          end
        end
      end
    end
    slots
  end

  def festival_params
    params.require(:festival).permit(:name, :location, :start_date, :end_date, :photo,
    love_pod_ids: [], available_slot_ids: [])
  end

  def available_slot_params
    params.require(:available_slot).permit(:date, :time_frame, :start_time, :duration,
    :festival_id, :love_pod_id)
  end
end

app/helpers/festivals_helper.rb
module FestivalsHelper
end

app/views/festivals/check_availability.html.erb
<%# This form allows users to re-check availability without going back %>
<div class="check-container">
  <%= form_with url: check_availability_festival_path(@festival), method: :get, local: true do |form| %>
    <div class="field">
      <%= form.label :date, "Select Date" %>
      <%= form.select :booking_date, options_for_select(@date_options, @date), required: true %>
    </div>
    <div class="field">
      <%= form.label :duration, "Duration (minutes)" %>
      <%= form.select :duration, options_for_select([25, 55], @duration), required: true %>
    </div>
    <%= form.submit "Show available time slots", class: 'butt button-pink' %>
  <% end %>
</div>

<%# Displaying the available slots %>
<% if @date.present? && @duration.present? && @festival_slots.present? %>
  <h3>Available time slots on <%= Date.parse(@date).strftime('%a %d %b %Y') %>:</h3>

  <% filtered_slots = @festival_slots.select do |slot|
    slot.date.to_date == @date.to_date &&
    slot.duration == @duration
  end.sort_by(&:time_frame) %>

  <% booked_slots = @festival_slots.select do |slot|
    Booking.exists?(available_slot_id: slot.id)
  end %>

  <% free_slots = filtered_slots.reject do |filtered|
      booked_slots.any? do |booked|
      (booked.duration == 55 && filtered.duration == 25 &&
      booked.date == filtered.date &&
      booked.love_pod == filtered.love_pod &&
      booked.start_time + 30.minutes == filtered.start_time) ||

      (booked.date == filtered.date &&
      booked.love_pod == filtered.love_pod &&
      booked.start_time == filtered.start_time)
    end
  end %>

  <% unique_free_slots = free_slots.group_by(&:time_frame).map do |time_frame, slots|
    slots.first
  end %>

  <div class="slots-list">
    <% if unique_free_slots.present? %>
      <% unique_free_slots.group_by(&:time_frame).each do |time_frame, slots| %>
        <% slots.each do |slot| %>
          <div class="slot-element">
            <div class="time-frame"><%= slot.time_frame %> (<%= humanized_money_with_symbol(slot.price) %>)</div>
            <%= link_to "Book a slot", new_festival_booking_path(
              festival_id: @festival.id,
              booking_date: slot.date,
              start_time: slot.start_time,
              duration: slot.duration,
              available_slot_id: slot.id,
              love_pod: slot.love_pod,
              slots_sku: slot.sku,
              amount: slot.price
            ), class: 'butt button-green' %>
          </div>
        <% end %>
      <% end %>
    <% else %>
      <p class="grey-text">No available slots for the selected date and duration.</p>
    <% end %>
  </div>
<% else %>
  <p class="grey-text">No available time slots for the selected date and duration.</p>
<% end %>

<%= link_to "Back to festival", festival_path(@festival), class: "butt button-white" %>
</div>

app/views/festivals/edit.html.erb
<% if user_signed_in? && current_user.admin? %>

  <h1 class="page-title">Edit Festival</h1>

  <%= form_with(model: @festival, local: true, html: { class: 'festival-form' }) do |form| %>
    <% if @festival.errors.any? %>
      <div id="error_explanation" class="errors">
        <h2><%= pluralize(@festival.errors.count, "error") %> prohibited this festival from being saved:</h2>
        <ul>
        <% @festival.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name, class: 'form-label' %>
      <%= form.text_field :name, id: :festival_name, class: 'form-input' %>
    </div>

    <div class="field">
      <%= form.label :location, class: 'form-label' %>
      <%= form.text_field :location, id: :festival_location, class: 'form-input' %>
    </div>

    <div class="field">
      <%= form.label :start_date, class: 'form-label' %>
      <%= form.date_field :start_date, id: :festival_start_date, class: 'form-input' %>
    </div>

    <div class="field">
      <%= form.label :end_date, class: 'form-label' %>
      <%= form.date_field :end_date, id: :festival_end_date, class: 'form-input' %>
    </div>

    <div class="field">
      <%= form.label :love_pods, "Select Love Pods", class: 'form-label' %>
      <%= form.collection_select :love_pod_ids, LovePod.all, :id, :name, {}, {multiple: true, size: 10} %>
    </div>

    <div class="actions">
      <%= form.submit 'Save', data: { confirm: 'Be careful when removing festival dates or love pods - this could lead to the cancellation of pre-existing bookings.' }, class: 'button' %>
    </div>

  <% end %>

  <%= link_to 'Back to festival', festival_path(@festival), class: 'back-link' %>

<% else %>
  <p>You are not authorized to see this page.</p>
<% end %>

app/views/festivals/index.html.erb
<!--<h1 class="page-title">Festivals</h1>-->

<div class="cards-list">
  <% @festivals.each do |festival| %>
    <div class="card card-spacing">
      <h2 class="festival-name"><%= link_to festival.name, festival_path(festival) %></h2>
      <div class="festival-description">
          <% if festival.photo.attached? %>
            <%= cl_image_tag(festival.photo.key) %>
          <% else %>
            <%= cl_image_tag(festival.image_url) %>
          <% end %>
        <p class="festival-dates"><%= festival.start_date.strftime('%a %d %b %Y') %>
          to <%= festival.end_date.strftime('%a %d %b %Y') %></p>
        <p class="festival-location"><%= festival.location %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/festivals/new.html.erb
<% if user_signed_in? && current_user.admin? %>

  <h1 class="page-title">Add a new festival</h1>

  <%= form_with(model: @festival, local: true) do |form| %>
    <% if @festival.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@festival.errors.count, "error") %> prohibited this festival from being saved:</h2>

        <ul>
          <% @festival.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :festival_name %>
    </div>

    <div class="field">
      <%= form.label :location %>
      <%= form.text_field :location, id: :festival_location %>
    </div>

    <div class="field">
      <%= form.label :start_date %>
      <%= form.date_field :start_date, id: :festival_start_date %>
    </div>

    <div class="field">
      <%= form.label :end_date %>
      <%= form.date_field :end_date, id: :festival_end_date %>
    </div>

    <div class="field">
      <%= form.label :love_pods, "Select Love Pods", class: 'form-label' %>
      <%= form.collection_select :love_pod_ids, LovePod.all, :id, :name, {}, {multiple: true, size: 10} %>
    </div>

    <div class="field">
      <%= form.label :photo %>
      <%= form.file_field :photo, id: :festival_photo %>
    </div>

  <div class="butt-list">
      <%= form.submit class:"butt button-pink" %>
    <% end %>

    <%= link_to 'Back to Festivals', festivals_path, class:"butt button-white" %>
  </div>

<% else %>
  <p>You are not authorized to see this page.</p>
<% end %>

app/views/festivals/show.html.erb
<div class="card festival-details">
  <% if @festival.photo.attached? %>
    <%= cl_image_tag(@festival.photo.key) %>
  <% else %>
    <%= cl_image_tag(@festival.image_url) %>
  <% end %>
  <h2><%= @festival.name %></h2>

  <div class="festival-info">
    <p><strong>Dates:</strong> <%= @festival.start_date.strftime('%a %d %b %Y') %> to <%= @festival.end_date.strftime('%a %d %b %Y') %></p>
    <p><strong>Location:</strong> <%= @festival.location %></p>
  </div>

  <div class="festival-love-pods">
    <h3>Love Pods at this Festival</h2>
      <% if @festival.love_pods.any? %>
      <div class="butt-list love-pods-list">
          <% @festival.love_pods.each do |love_pod| %>
              <%= link_to love_pod.name, festival_love_pod_path(@festival, love_pod) %>
          <% end %>
      </div>
      <% else %>
        <p>No Love Pods available for this festival.</p>
      <% end %>
  </div>


  <div class="butt-list">
    <%= link_to 'Check availability', check_availability_festival_path(@festival), class: 'butt button-pink' %>
    <%= link_to 'Back to Festivals', festivals_path, class: 'butt button-white' %>
    <% if user_signed_in? && current_user.admin? %>
      <%= link_to 'Edit', edit_festival_path(@festival), class: 'butt button-blue' %>
      <%= link_to 'Delete', festival_path(@festival), method: :delete, data: { confirm: 'Are you sure?' }, class: 'butt button-blue' %>
    <% end %>

  </div>
</div>